apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
type: Opaque
stringData:
  MYSQL_USER: "admin"
  MYSQL_PASSWORD: "8888313545"
  MYSQL_HOST: "database-1.cglioew4ktr8.us-east-1.rds.amazonaws.com"
  MYSQL_DB: "test"
